import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect } from "react";
import { Loader2 } from "lucide-react";
import { TopBar } from "@/components/TopBar";
import { BottomNav } from "@/components/BottomNav";
import { SurahPath } from "@/components/SurahPath";

import { useAuth } from "@/hooks/useAuth";
import { useProfile } from "@/lib/profile";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Nour — Apprends le Coran en t'amusant" },
      { name: "description", content: "Apprends les sourates du Coran à travers des leçons courtes et ludiques. Écoute, associe, complète." },
      { property: "og:title", content: "Nour — Apprends le Coran" },
      { property: "og:description", content: "Une approche gamifiée pour apprendre le Coran, sourate par sourate." },
    ],
  }),
  component: Index,
});

function Index() {
  const { user, ready: authReady } = useAuth();
  const { profile, ready: profReady } = useProfile();
  const navigate = useNavigate();

  // Login is mandatory: redirect to /login then /onboarding if needed.
  useEffect(() => {
    if (!authReady) return;
    if (!user) {
      navigate({ to: "/login" });
      return;
    }
    if (profReady && profile) {
      const looksAutoGenerated = /^user[0-9a-f]{6,}$/i.test(profile.username);
      const noName = !profile.display_name || profile.display_name.trim().length < 2;
      if (looksAutoGenerated || noName) navigate({ to: "/onboarding" });
    }
  }, [authReady, user, profile, profReady, navigate]);

  if (!authReady || !user) {
    return (
      <div className="min-h-screen grid place-items-center">
        <Loader2 className="w-6 h-6 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col">
      <TopBar />
      <main className="flex-1">
        <SurahPath />
      </main>
      <BottomNav />
    </div>
  );
}

