/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardrobeRouteImport } from './routes/wardrobe'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ChestsRouteImport } from './routes/chests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizJuzIdRouteImport } from './routes/quiz.$juzId'
import { Route as MemorizeSurahIdRouteImport } from './routes/memorize.$surahId'
import { Route as LessonSurahIdRouteImport } from './routes/lesson.$surahId'
import { Route as ExamSurahIdRouteImport } from './routes/exam.$surahId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const WardrobeRoute = WardrobeRouteImport.update({
  id: '/wardrobe',
  path: '/wardrobe',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestsRoute = ChestsRouteImport.update({
  id: '/chests',
  path: '/chests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizJuzIdRoute = QuizJuzIdRouteImport.update({
  id: '/quiz/$juzId',
  path: '/quiz/$juzId',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorizeSurahIdRoute = MemorizeSurahIdRouteImport.update({
  id: '/memorize/$surahId',
  path: '/memorize/$surahId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonSurahIdRoute = LessonSurahIdRouteImport.update({
  id: '/lesson/$surahId',
  path: '/lesson/$surahId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSurahIdRoute = ExamSurahIdRouteImport.update({
  id: '/exam/$surahId',
  path: '/exam/$surahId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chests': typeof ChestsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/premium': typeof PremiumRoute
  '/stats': typeof StatsRoute
  '/wardrobe': typeof WardrobeRoute
  '/api/chat': typeof ApiChatRoute
  '/exam/$surahId': typeof ExamSurahIdRoute
  '/lesson/$surahId': typeof LessonSurahIdRoute
  '/memorize/$surahId': typeof MemorizeSurahIdRoute
  '/quiz/$juzId': typeof QuizJuzIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chests': typeof ChestsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/premium': typeof PremiumRoute
  '/stats': typeof StatsRoute
  '/wardrobe': typeof WardrobeRoute
  '/api/chat': typeof ApiChatRoute
  '/exam/$surahId': typeof ExamSurahIdRoute
  '/lesson/$surahId': typeof LessonSurahIdRoute
  '/memorize/$surahId': typeof MemorizeSurahIdRoute
  '/quiz/$juzId': typeof QuizJuzIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chests': typeof ChestsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/premium': typeof PremiumRoute
  '/stats': typeof StatsRoute
  '/wardrobe': typeof WardrobeRoute
  '/api/chat': typeof ApiChatRoute
  '/exam/$surahId': typeof ExamSurahIdRoute
  '/lesson/$surahId': typeof LessonSurahIdRoute
  '/memorize/$surahId': typeof MemorizeSurahIdRoute
  '/quiz/$juzId': typeof QuizJuzIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chests'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/planner'
    | '/premium'
    | '/stats'
    | '/wardrobe'
    | '/api/chat'
    | '/exam/$surahId'
    | '/lesson/$surahId'
    | '/memorize/$surahId'
    | '/quiz/$juzId'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chests'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/planner'
    | '/premium'
    | '/stats'
    | '/wardrobe'
    | '/api/chat'
    | '/exam/$surahId'
    | '/lesson/$surahId'
    | '/memorize/$surahId'
    | '/quiz/$juzId'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/chests'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/planner'
    | '/premium'
    | '/stats'
    | '/wardrobe'
    | '/api/chat'
    | '/exam/$surahId'
    | '/lesson/$surahId'
    | '/memorize/$surahId'
    | '/quiz/$juzId'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChestsRoute: typeof ChestsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlannerRoute: typeof PlannerRoute
  PremiumRoute: typeof PremiumRoute
  StatsRoute: typeof StatsRoute
  WardrobeRoute: typeof WardrobeRoute
  ApiChatRoute: typeof ApiChatRoute
  ExamSurahIdRoute: typeof ExamSurahIdRoute
  LessonSurahIdRoute: typeof LessonSurahIdRoute
  MemorizeSurahIdRoute: typeof MemorizeSurahIdRoute
  QuizJuzIdRoute: typeof QuizJuzIdRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wardrobe': {
      id: '/wardrobe'
      path: '/wardrobe'
      fullPath: '/wardrobe'
      preLoaderRoute: typeof WardrobeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chests': {
      id: '/chests'
      path: '/chests'
      fullPath: '/chests'
      preLoaderRoute: typeof ChestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$juzId': {
      id: '/quiz/$juzId'
      path: '/quiz/$juzId'
      fullPath: '/quiz/$juzId'
      preLoaderRoute: typeof QuizJuzIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorize/$surahId': {
      id: '/memorize/$surahId'
      path: '/memorize/$surahId'
      fullPath: '/memorize/$surahId'
      preLoaderRoute: typeof MemorizeSurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$surahId': {
      id: '/lesson/$surahId'
      path: '/lesson/$surahId'
      fullPath: '/lesson/$surahId'
      preLoaderRoute: typeof LessonSurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$surahId': {
      id: '/exam/$surahId'
      path: '/exam/$surahId'
      fullPath: '/exam/$surahId'
      preLoaderRoute: typeof ExamSurahIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChestsRoute: ChestsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlannerRoute: PlannerRoute,
  PremiumRoute: PremiumRoute,
  StatsRoute: StatsRoute,
  WardrobeRoute: WardrobeRoute,
  ApiChatRoute: ApiChatRoute,
  ExamSurahIdRoute: ExamSurahIdRoute,
  LessonSurahIdRoute: LessonSurahIdRoute,
  MemorizeSurahIdRoute: MemorizeSurahIdRoute,
  QuizJuzIdRoute: QuizJuzIdRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
